### ISSUE TITLE
undefined method `new_file'

### ISSUE THREAD

**Issue by steveholt55** [lyptt/struct#148]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version
2.2.1

## Spec version
2.2.1

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context
Running struct generate through Jenkins is giving me this error:
```
struct generate
Processing project 'project'...
undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ffe01baf958>
```

I'm also using Fastlane to invoke struct generate, and running the same fastlane lane after copying the Jenkins workspace contents to a different folder works fine.  This error only happens when running through Jenkins. 

## Expected result
Expected project file to be created 

## Actual result
`undefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ffe01baf958>` error

**Comment by lyptt** [comment]
Hi @steveholt55, thanks for filing this issue. Would you be able to upload your project.yml so I can take a look? Either that or a simple test case would be very helpful. Thanks!

**Comment by steveholt55** [comment]
@lyptt - This is an example of my project.yml.  I had to change a few things related to my project but this is the gist of what I'm doing. [project.txt](https://github.com/workshop/struct/files/1301090/project.txt).  I'm also using this for Jenkins (`https://github.com/stisti/jenkins-app`)

**Comment by lyptt** [comment]
Thanks for this! I think this may just be purely an indentation issue. Unfortunately the error struct is giving here isn't that helpful. Line 36 should be two spaces to the left in order to ensure it contains the 'sources' statement, rather than sitting alongside it.

Would you mind giving that a try?

**Comment by lyptt** [comment]
I'm closing this issue for now, @steveholt55 please let me know if you're still having issues!

**Comment by steveholt55** [comment]
@lyptt I'm still having issues with this, updated to struct 3.1.0 and I'm still getting the error.  It isn't the spacing issue because I'm able to run struct perfectly if I just cd to my Jenkins directory. The issue only happens when running the struct command inside of Jenkins.  Also the spacing issue was just because I was changing some of the real values before I attached it here and didn't look over it close enough.

**Comment by steveholt55** [comment]
This is the full stack trace I get.  You're seeing lots of fastlane because I'm running struct from fastlane.

```
Processing project 'project'...
[31mundefined method `new_file' for #<Xcodeproj::Project::Object::PBXFileReference:0x007fe3da879e28>[0m
[0m
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/helper/sh_helper.rb:14:in `sh_no_action'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/fast_file.rb:180:in `block in sh'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/fast_file.rb:179:in `sh'
	from Fastfile:61:in `block (2 levels) in parsing_binding'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:34:in `block (2 levels) in parsing_binding'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:108:in `block (3 levels) in parsing_binding'
	from Fastfile:104:in `each'
	from Fastfile:104:in `block (2 levels) in parsing_binding'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.62.0/bin/fastlane:20:in `<top (required)>'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brandonjenniges/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by steveholt55** [comment]
@lyptt I added a test project demonstrating the issue [folder.zip](https://github.com/lyptt/struct/files/1395910/folder.zip).  Note that after extracting the .zip you'll see a folder called `non_hidden`. There is also a folder that is hidden called `.example` Both folders should have identical contents, the only difference is one is hidden and the other is not.

Running `cd .example/project;struct generate;` from the root extracted folder yields this error for me: 

```
undefined method `new_file' for <PBXFileReference path=`folder1` UUID=`D6789A7925358B92B4143AE2`>:Xcodeproj::Project::Object::PBXFileReference
```

But running `cd non_hidden/project;struct generate;` from the root works perfectly fine.

**Comment by lyptt** [comment]
Hi @steveholt55, thanks for the sample project! I'll check this out and see what's going on.

**Comment by lyptt** [comment]
I believe I've identified a fix for this issue, thanks for the additional help in reproducing this!

**Comment by steveholt55** [comment]
Verified this fixes my issue. Thanks!

**Comment by lyptt** [comment]
Great! I'll release a new version with this fix in shortly.
