### ISSUE TITLE
Wrong target naming when 'PRODUCT_NAME' setting is presented

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#161]
## New Issue Checklist

- [x ] Updated struct to the latest version
- [ x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

3.1.2

## Spec version

2.1.0

## Which type of spec are you using?

- [ x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

When target has 'PRODUCT_NAME' build setting set to a custom value (different from target name), then this value is used as target name, which is UNEXPECTED/NON-OBVIOUS behaviour.

## Reproduction steps

Create simple project spec, add there "MyTarget" target, in configurations add "PRODUCT_NAME" setting equal to "XYZMyTarget". Run "struct generate" and in the resulting project...

## Expected result

...it should be named "MyTarget",...

## Actual result

... but, instead, the target will be named "XYZMyTarget".

**Comment by lyptt** [comment]
In order to change your PRODUCT_NAME, simply change the name of the target. The two are intrinsically linked in Struct and it's not currently supported to make target names and product names inconsistent with one another

**Comment by maximkhatskevich** [comment]
Thanks for letting me know. That's actually sad. I use this property a lot, it's important to be able distinguish them for me. @lyptt do you mean it's not even considered as a bug that you would fix anytime soon?

**Comment by lyptt** [comment]
Hi @maximkhatskevich, currently that's Struct's behaviour, however I can understand why that might be problematic. I have a suspicion the reason I didn't apply this behaviour was due to internal mechanisms between Xcode and the Xcodegen gem conflicting when attempting to separate these properties out. The result of this is was that searching for targets to link against would fail, which prevented a lot of Struct's use cases working.

I'll investigate in more depth this week, and hopefully have a more thorough answer for you.

**Comment by maximkhatskevich** [comment]
@lyptt okay, thanks for more details. Please, note, that this issue is not presented in pre-3.* version. As a temporary solution - I rolled back to 2.2.1.

**Comment by tomachinz** [comment]
an example project.yml file would help anybody know of the location of one? like with
MyApp: "ExampleApplication"
etc

**Comment by steveholt55** [comment]
This issue seems to be affecting me as well.  I've also noted that rolling back to 2.2.1 fixes this issue for me but I need some of the fixes in the 3.X releases.

**Comment by lyptt** [comment]
I'll have a look at this over the weekend, hopefully it's simple to resolve 👍

**Comment by maximkhatskevich** [comment]
Looks like we are stuck here. Again, in my experience, this issue does not happen with Struct < 3.0, in particular v.2.2.1 works just fine, but, I believe, the root of this issue is in this commit https://github.com/lyptt/struct/commit/3ff73e46dda93af07ddf1bf6570dd14b6d03496e which is actually before v.2.2.1 has happened if you look in [commits history](https://github.com/lyptt/struct/commits/master?after=4fa995769ebd59968b8cb869ab686ac6b7195b09+34).

**Comment by maximkhatskevich** [comment]
As a workaround, I make it work for me as following.

I do NOT set `PRODUCT_NAME` build setting in spec file on target level, letting it to be set to `$(TARGET_NAME)` by default. Instead I set this property on project level and then I add a lifecycle hook (in particular — post-generation script) where I edit final project file via Xcodeproj and just set `PRODUCT_NAME` setting on target level to `$(inherited)`. Usually it's needed for cross-platform frameworks — target names reflect their corresponding target platforms (like `macOS-MyFWK` and `iOS-MyFWK`, etc.), but desired module name should be the same across all platforms (something like `XYZMyFWK`).

I use script like this:
```ruby
# post-generate Struct script
# https://github.com/lyptt/struct/wiki/Spec-format:-v2.0#lifecycle-hooks

run do |spec, xcodeproj|

    # https://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/Project
    # https://github.com/CocoaPods/Xcodeproj/blob/master/spec/project/object/native_target_spec.rb

    xcodeproj
        .targets
        .select{ |t| ["com.apple.product-type.framework"].include?(t.product_type) }
        .each{ |t|

            t.build_configurations.each do |config|

                config.build_settings['PRODUCT_NAME'] = '$(inherited)'
            end
        }

    xcodeproj.save()

end
```

**Comment by lyptt** [comment]
Hi @maximkhatskevich , potentially you could also solve this by manually overriding the PRODUCT_NAME setting, e.g.:

```yaml
  my-framework:
    type: ":framework"
    platform: ios
      sources:
      - src
     configurations:
       $base:
         PRODUCT_NAME: MyFramework
```

**Comment by maximkhatskevich** [comment]
@lyptt thanks for the advice, but I'm not sure I get it. First of all, what is this `$base` configuration identifier? I didn't know it exists, I only saw this key in `variants` section. And anyway, if I set `PRODUCT_NAME` explicitly in this section of spec, then Struct uses this value for the target name (see the commit I mentioned earlier), which is not what I want and will lead to a corrupted Xcode project file, because multiple targets will be named the same. This is why I ended up using lifecycle hooks to adjust the property after Struct already generated project file.

P.S. maybe I should use the 'variants' section to override `PRODUCT_NAME` property in certain targets and not using hooks at all?

**Comment by yonaskolb** [comment]
This is similar to the problem I was having in #146

**Comment by lyptt** [comment]
Hi @maximkhatskevich, I've just had a look through the issue in its entirety. I think this comes down to our target resolution process, whereby targets are looked up by their PRODUCT_NAME when adding target dependencies, which explains why the two are intrinsically linked.

As explained in the readme I'm unable to work on struct directly at present, however pull requests are definitely welcomed. The only alternative for now is using consistent naming between the internal target name and PRODUCT_NAME.

**Comment by maximkhatskevich** [comment]
@lyptt no problem, as I explained above - I found a workaround with lifecycle hooks, and it's not a big deal, especially considering great value which Struct brings to my workflow overall.

P.S. I think we should keep this issue open so that people who encounter similar issue could easily find this thread.

**Comment by lyptt** [comment]
Closing this for now until there is further interest in changing this behaviour.
