### ISSUE TITLE
More customization options with i18n-resources

### ISSUE THREAD

**Issue by steveholt55** [lyptt/struct#163]
I'm wondering if it would be possible to add the ability to have some extra customization to which Strings files get included?  Much like how source files have an includes/excludes option.  I'm saying this because how I use struct is to build multiple different apps that may or may not have support for all of the languages that I have localization files for.

**Comment by lyptt** [comment]
As far as I'm aware standard excludes sections are processed for i18n_resources in the same vain as sources, I'll double check this though! If the functionality isn't there already it's fairly simple to add.

**Comment by steveholt55** [comment]
Thanks for taking a look at this.  I was able to test this out but I'm still unable to figure out how to make it work.  I've attached a sample project [lang_test.zip](https://github.com/lyptt/struct/files/1827807/lang_test.zip) that attempts to exclude one of the 2 language folders include in the directory.  Please let me know if you see something wrong with my project.yml.  I'll take a look and see if I can add this functionality if it does not already exist.

**Comment by lyptt** [comment]
@steveholt55 thanks for attaching a sample project, I'll see what's going on

**Comment by lyptt** [comment]
This appears to no longer be happening on the latest version of struct. Please let me know if it's still an issue for you.
