### ISSUE TITLE
Can't add .tbd libraries to project

### ISSUE THREAD

**Issue by steveholt55** [lyptt/struct#165]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

3.1.2

## Spec version

2.1.0

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

I'm trying to add a couple of .tbd libraries to my project because of a third party library having a requirement to use them.  My guess is that I'm incorrectly added this to the project.yml but I'm unsure how I added it differently. Sample project - [project.zip](https://github.com/lyptt/struct/files/1964477/testtest.zip)

## Reproduction steps

I've tried adding the library to the references like this.

`references:
    - sdkroot:libiconv.tbd
`

## Expected result

Library gets added the the project file

## Actual result

`ld: library not found for -llibiconv.tbd` and if I go into the general tab the library that was attempted to added gets an extra "lib" prefixed.  I.e. "liblibconv.tbd".

**Comment by janhalousek** [comment]
Same issue here. @steveholt55 have you found way around it?

**Comment by lyptt** [comment]
Hey @steveholt55. Really sorry about the delay on this one. As far as I'm aware this is definitely supported, however it's not clearly documented which I'll address this week.

In order to link to non-framework system libraries, you omit the `lib` part, and the file extension, but otherwise it remains the same as frameworks, for example:

```yaml
    references:
    - sdkroot:iconv
```

I've attached a full example that builds in Xcode with iconv as a dependency. Hope that helps!

[stest.zip](https://github.com/lyptt/struct/files/2441412/stest.zip)

**Comment by lyptt** [comment]
@janhalousek you should be able to use this approach for any system library you're trying to link to also.

**Comment by janhalousek** [comment]
@lyptt thanks for getting back to us. Unfortunately, using your documented approach (also tried your test project), system libraries get translated to `.dylib` referencies, which has been obsolete for few versions of XCode now.
Is there a way to reference `.tbd` libraries? 
Thank you

**Comment by lyptt** [comment]
@janhalousek as far as I remember although it has the dylib in the name, it's still essentially the same thing. Can you try it and see if it works?

I will have a look into how I do system library resolution, its implementation was done all the way back in Struct 1.0.0 so maybe it needs some tweaking.

**Comment by janhalousek** [comment]
Yes, I think its usage might be the same, although the problem is that XCode nowadays has only tbd libraries bundled inside, so any path to dylib version of library is invalid. At least on my side :)

**Comment by lyptt** [comment]
@janhalousek did Xcode fail to build after applying the above change to the project.yml? In my sample project Xcode appears to build and link the application fine with a dylib there.

**Comment by lyptt** [comment]
This appears to also be functionality that's inherited by the [Xcodeproj](https://github.com/CocoaPods/Xcodeproj) project, as I just call `target_dsl.add_system_library [ref.name]`. Maybe a version bump would change this behaviour.

**Comment by lyptt** [comment]
From the sounds of things this issue is resolved - please let me know if there's still complications here!
