### ISSUE TITLE
Support for application.watchapp2-container

### ISSUE THREAD

**Issue by tkafka** [lyptt/struct#171]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

3.2.1

## Spec version

2.1.0

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

Apple has added a way to create independent watch apps in WatchOS 6. If you select "Watch app" in a New project wizard, you will get a project with a 
- the ususal watchkit / watchkit extension targets
- new type of target called `application.watchapp2-container` which seems to replace previous 'master' iOS app, and serves as a kinda 'shadow' target (it can't be built or run, but if you delete it, the watch/simulator won't run the WatchOS app).

This is how it looks like:

<img width="713" alt="Screenshot 2020-05-13 at 09 48 18" src="https://user-images.githubusercontent.com/876717/81785721-e9014500-94fe-11ea-872e-608f42762973.png">

<img width="628" alt="Screenshot 2020-05-13 at 09 49 56" src="https://user-images.githubusercontent.com/876717/81785853-21a11e80-94ff-11ea-9b74-80147a039435.png">

Currently there seems to be no way to create this `application.watchapp2-container` or to migrate it:

    struct migrate -p ./myproject.xcodeproj
    Warning: unrecognised project configuration profile 'application.watchapp2-container'. Ignoring...

## Reproduction steps

- create a xcode project with 'Watch app' (without iOS counterpart) wizard
- try to migrate it to `spec`

## Expected result

- spec handles the watchapp2-container and creates a profile correctly

## Actual result

- spec ignores this target as it doesn't know it

**Comment by lyptt** [comment]
Hey @tkafka, thanks for filing this issue. This shouldn't be too hard to add support for, I'll aim to get something released by the end of the week that adds this in.

**Comment by lyptt** [comment]
This is now released with v4.0.0. If you notice any further issues, please feel free to file an issue 🙂
