### ISSUE TITLE
Merge Xcake into this

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#22]
Hey so I've been working on something similar for the last year and I think rather than us competing it would be great for maybe my project to merge some of its features into this one.

😀 It already has things like the DSL you would like so it would be interesting to see where we can collaborate 

Here is the link to my repo https://github.com/jcampbell05/xcake

**Comment by lyptt** [comment]
Hey @jcampbell05, thanks for filing this issue.

I'm definitely open to this! It seems like our projects have similar goals, and the more contributors on this project, the better in my opinion.

I'm just about finished up with the `struct` DSL, however looking over your DSL I've noticed it's much higher level than `struct`'s. I'd propose us breaking down which features each tool has, and seeing what's a good fit. For example, your DSL could act as a 'superset' of what's currently in `struct` to make simple use cases for project definition even simpler.

**Comment by jcampbell05** [comment]
@lyptt Sounds like a plan.

So currently I have a list of what can be done in the Xcake DSL here:
https://github.com/jcampbell05/xcake/blob/master/docs/Xcode%20Project%20Support.md

Here is the syntax reference to help understand how this translates to our DSL:
https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md

**Comment by lyptt** [comment]
From what I can see on the documentation you've provided, there's a few areas that `struct` currently doesn't approach:

- Setting class prefixes - Objective-C support is still quite new to `struct`, so this will need adopting. This tool is primarily aimed at Swift projects, so this functionality has yet to be added.
- Setting organization information

There's other areas that I'm not certain `struct` needs to support:
- Configuring schemes - the current approach with schemes has been to have these generated for you by build tools like Fastlane, and automatically when working with your project from within Xcode. Schemes are only really needed for build tools, as these are generated by Xcode as soon as you open a project file, and tools like Fastlane have ways to do this automatic generation for you (see [recreate_schemes](https://docs.fastlane.tools/actions/#recreate_schemes))
- Set primary language - I don't believe this affects anything in Xcode projects, Xcode most likely has sensible default behaviour when this is unset
- Specify device - This has a sensible default in Xcode, and is stored in a user's internal xcworkspace
- Additional build phases (headers/copy files) - As explained in [Migrating Xcode projects](https://github.com/lyptt/struct/wiki/Migrating-Xcode-projects), the ethos behind `struct` is to keep your project files as simple as possible, and for it to be very easy to reason about how your project works and is structured. I feel that additional build phases complicate projects more than I'm currently happy with. I'm happy to discuss this further however.

And finally, the main things I'd like to bring in for the DSL _and_ existing YAML/JSON formats:

- Simple methods for creating targets
- Simple methods for creating tests

Everything else you've listed is supported by `struct`, so no action needed there.

**Comment by jcampbell05** [comment]
> From what I can see on the documentation you've provided, there's a few areas that struct currently doesn't approach:
> 
> Setting class prefixes - Objective-C support is still quite new to struct, so this will need adopting. This tool is primarily aimed at Swift projects, so this functionality has yet to be added.
> Setting organization information

Awesome I'll look into how to achieve these.

> There's other areas that I'm not certain struct needs to support:
> 
> Configuring schemes - the current approach with schemes has been to have these generated for you by build tools like Fastlane, and automatically when working with your project from within Xcode. Schemes are only really needed for build tools, as these are generated by Xcode as soon as you open a project file, and tools like Fastlane have ways to do this automatic generation for you (see recreate_schemes)

So the reason we have this is some users build libraries where they need custom schemes outside of the one per target and would like one per target and scheme so they can have a "App-Debug" or "App-Release"

> Set primary language - I don't believe this affects anything in Xcode projects, Xcode most likely has sensible default behaviour when this is unset

True, I was considering deprecating this in Xcake.

> Specify device - This has a sensible default in Xcode, and is stored in a user's internal xcworkspace

This was to specify if an App supports iPhone, iPad or is a Universal App.

> Additional build phases (headers/copy files) - As explained in Migrating Xcode projects, the ethos behind struct is to keep your project files as simple as possible, and for it to be very easy to reason about how your project works and is structured. I feel that additional build phases complicate projects more than I'm currently happy with. I'm happy to discuss this further however.

So for some people using Xcake currently I know they like the ability to still specify build phases for scripts (Some use this to run swiftlint).

Headers which is useful for those who use it for building frameworks as they can expose public header files (otherwise impossible to use Xcake for framework developers) and I've recently started adding the ability to embed frameworks to Xcake as some people need that for their app.

But I guess it will be interesting to know where you see Struct within the ecosystem. For Xcake I've always built it as something you can use standalone, i.e I don't assume you use Cocoapods or Fastlane nor that you use any version of Ruby than 2.0.  

That said, I obviously tried to stick to just handling the project generation.

> And finally, the main things I'd like to bring in for the DSL and existing YAML/JSON formats:
> 
> Simple methods for creating targets
> Simple methods for creating tests
> Everything else you've listed is supported by struct, so no action needed there.

Awesome, I can have a look at how I can port the higher level methods from Xcake into Struct.

**Comment by jcampbell05** [comment]
Also I have a fastlane plugin I can contribute :)

**Comment by lyptt** [comment]
@jcampbell05 thanks for the answers, very helpful!

For specifying the device, isn't this usually controlled by a plist setting? I may be misremembering however. If it's configured on a target level, we can definitely add it in!

For swiftlint, you can use the 'scripts' functionality currently built into struct. These are the only phases struct currently supports adding to a project, due to their necessity. These take inspiration from package.json from the NodeJS world.

In regards to custom schemes, what problem are these trying to solve? If you're after having multiple flavours of a target, struct has a feature called 'variants' which allow for this. Also, for things like detecting which configuration you're on and adjusting the behaviour of your code accordingly, you can use the build setting `SWIFT_ACTIVE_COMPILATION_CONDITIONS` on a configuration level. I may be misunderstanding, so some clarification will definitely help!

Embedding frameworks has been supported since day 1, and is completely seamless in struct. It can pick up any framework in one of your `source_dir` entries and it'll do all of the configuration for you. In my current use of this tool on we simply add Carthage's Build directory as a `source_dir` entry and struct does the rest 👍

I definitely see struct as part of a larger whole, rather than standing alone. Tools like Carthage and Fastlane are becoming industry-standard, just like CocoaPods has been for some time now. I want struct to have a place within that ecosystem, rather than attempting to establish its own.

For Ruby 2.0, I did a preliminary investigation, but I'm not 100% comfortable with the huge refactor it'd involve to downgrade. There may be alternatives like the way Calabash can establish a ruby sandbox without needing a specific version of ruby to be installed.

**Comment by lyptt** [comment]
@jcampbell05 A Fastlane plugin sounds like a great idea! One of the workflows I intended struct to be used in was where xcodeproj files would be gitignored and generated as part of an automated build process, so a simple means of achieving this in an automated fashion would be a great thing indeed 👍

**Comment by lyptt** [comment]
@jcampbell05 [Traveling ruby](https://phusion.github.io/traveling-ruby) may be a decent option to simplify the installation of this tool. This way we can package up the required version of ruby with the ruby runtime itself.

This packaged build could then be registered via [Homebrew](https://brew.sh/) much like Fastlane currently is. This should make the tool much more accessible to people that aren't as involved in the Ruby ecosystem.

**Comment by maximkhatskevich** [comment]
@lyptt you may find it useful to take a look on this (very short) conversation about pros and cons of why you would like to gitignore or not the project file if you are using project generation tool like Xcake or Struct: https://github.com/jcampbell05/xcake/issues/141#issuecomment-280148162

**Comment by lyptt** [comment]
@maximkhatskevich Yeah, I agree with the sentiments there. I actually use both workflows myself, it really depends on your needs for your CI environment, and there's two schools of thought on how to approach this kind of tooling. Good to see it's not just me thinking about this!

**Comment by lyptt** [comment]
@jcampbell05 If you're unhappy about continuing with integrating Xcake into this repository, I'll go ahead and close this issue for now.

I'd prefer to work together than apart, but it's entirely up to you 😀

**Comment by jcampbell05** [comment]
@lyptt :) so I agree 

> For specifying the device, isn't this usually controlled by a plist setting? I may be misremembering however. If it's configured on a target level, we can definitely add it in!
> 
> For swiftlint, you can use the 'scripts' functionality currently built into struct. These are the only phases struct currently supports adding to a project, due to their necessity. These take inspiration from package.json from the NodeJS world.

Okay that makes sense :)

> 
> In regards to custom schemes, what problem are these trying to solve? If you're after having multiple flavours of a target, struct has a feature called 'variants' which allow for this. Also, for things like detecting which configuration you're on and adjusting the behaviour of your code accordingly, you can use the build setting SWIFT_ACTIVE_COMPILATION_CONDITIONS on a configuration level. I may be misunderstanding, so some clarification will definitely help!
> 

so I think there are two types of people, people who like there schemes to be per target i.e "MyApp" and what build settings it uses depends on the build method.

And those who like to have a scheme per target and build configuration combination so they can easily select the target and build configuration from the scheme list.

> Embedding frameworks has been supported since day 1, and is completely seamless in struct. It can pick up any framework in one of your source_dir entries and it'll do all of the configuration for you. In my current use of this tool on we simply add Carthage's Build directory as a source_dir entry and struct does the rest 👍
> 

Does this work for products of targets in the project ?

> I definitely see struct as part of a larger whole, rather than standing alone. Tools like Carthage and Fastlane are becoming industry-standard, just like CocoaPods has been for some time now. I want struct to have a place within that ecosystem, rather than attempting to establish its own.
> 
 For Ruby 2.0, I did a preliminary investigation, but I'm not 100% comfortable with the huge refactor it'd involve to downgrade. There may be alternatives like the way Calabash can establish a ruby sandbox without needing a specific version of ruby to be installed.
> 

Do we know what that would involve ? I would be happy to try and dedicate some time to see if we could get it running on Ruby 2.0. In Xcake I just had to backport one class for it to work from what I remember. 

Also do you support setting the name of the project file generated ?

**Comment by jcampbell05** [comment]
> @jcampbell05 If you're unhappy about continuing with integrating Xcake into this repository, I'll go ahead and close this issue for now.
> 
> I'd prefer to work together than apart, but it's entirely up to you

Sure I would love to carry on working :) I may have to keep supporting Xcake for a little while as I know some people still use it and prefer it but I think we could benefit from working together and close the gap between the tools.

**Comment by lyptt** [comment]
Targets within the project can be added as references through a manual declaration, in the DSL this would be `target_reference 'target_name'`

I think my solution of bundling struct up with ruby and distributing it may be the simpler option, and have less headaches in the future. This way we're not dependent on what version of ruby Apple ships with.

Setting project names is done quite easily with project variants, it's detailed in the [documentation](https://github.com/lyptt/struct/wiki/Specfile-format%3A-v1.2.0#variants). If you just wanted to have a custom project name, you could set $base to abstract, then define a variant with whatever name you wanted.

The convention for struct however is to use `project.xcodeproj` for generated projects, unless it's generating variants. This is where struct's more opinionated approach to project generation comes into play.

**Comment by lyptt** [comment]
Since the items discussed are more of a long-term goal, it's probably wise to break out any additions into separate issues / PRs, so I'll close this ticket for now. Thanks again for filing this issue, it's good to have your support!

**Comment by jcampbell05** [comment]
@lyptt cool :) I'll file some issues to help break these down. Excited to start becoming a contributor :)
