### ISSUE TITLE
Project variant name to keep letter case as in the project.yml

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#32]
Currently, if I declare project variant 'Main' Struct creates project file with name 'main.xcodeproj', so it's case insensitive and always convert the provided name into lower case, which is unexpected and undesired behavior. Having some letters in Capital helps to easier read the name of the project and follow overall project naming conventions.

Is there a way to preserve letter case as it is specified in the yml file or is it something that would be eliminated if I start using the new Specfile format based on Ruby?

**Comment by lyptt** [comment]
Hi @maximkhatskevich, good point! I'm perfectly happy to disable any transformation on the project file naming for variants. Expect this to be implemented soon!

**Comment by maximkhatskevich** [comment]
Okay, cool. Also, same rule would be good to apply for configuration names. Thanks!

**Comment by lyptt** [comment]
Hi @maximkhatskevich, we don't actually transform configuration names, they default to 'debug' and 'release' as this is the naming convention for most of struct's default project generation.

If you want differently named configurations, you can specify the configuration type - this behaves very similar to CocoaPods, for example:

```
---
configurations:
  Debug:
    type: debug
```

For more information about how configurations are defined, check out the [documentation](https://github.com/lyptt/struct/wiki/Spec-format%3A-v1.2.0#configurations).

**Comment by maximkhatskevich** [comment]
Okay, got it.

**Comment by maximkhatskevich** [comment]
By the way, @lyptt how do I specify type of a custom named Build Configuration in the new Ruby format (Specfile)?

something like this?

```Ruby
configuration('AppStore') do

    type 'release'
    profile 'general:release'
    profile 'ios:release'

end
```

or should it be `type :release` or `type ':release'`??

**Comment by lyptt** [comment]
Hi @maximkhatskevich, for the DSL you can specify things like 'type' as symbol (`:release`) or a string (`'release'`). The DSL is flexible in this regard so it's purely stylistic.

**Comment by maximkhatskevich** [comment]
Thanks! I do not know Ruby, only been using it with CocoaPods and Xcake so far, so I rely completely on examples :)

**Comment by lyptt** [comment]
Sure! When in doubt, use strings 🙂 I intend to fully document where symbols are accepted in the DSL soon!

**Comment by maximkhatskevich** [comment]
Okay, noted.
