### ISSUE TITLE
Apply build settings to all configurations at once

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#33]
When under a target you define build settings like this:

```Ruby
targets:
  FrameworkExample:
    sources: FrameworkExample
    platform: ios
    type: ":framework"
    profiles:
    - platform:ios
    - framework
    configuration:
      INFOPLIST_FILE: FrameworkExample/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.FrameworkExample
      ...
```

... and not like this:

```Ruby
---
version: 1.1.0
configurations:
  debug:
    profiles:
    - general:debug
    - ios:debug
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '9.1'
      ...
```

(defining build settings right under 'configuration', not under a 'configurations' and then under one of the specific configurations like 'Debug' or 'Release') - does it mean you apply these settings to all configurations at once or is it a bug in the example?

Based on that: https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml

**Comment by lyptt** [comment]
Yes this is indeed a feature of the spec format, you can apply the same configuration settings to all configuration profiles at once. You can take a look at the [documented sample project](https://github.com/lyptt/struct/blob/master/examples/iOS_Application/project.yml) to see this in more detail.

**Comment by maximkhatskevich** [comment]
Great, thanks!
