### ISSUE TITLE
How to make Struct start using the new Specfile format?

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#34]
I've prepared a Specfile, removed the project.yml file and executed `struct --generate` in Terminal, and go this: `Could not find project.yml or project.json in the current directory`

**Comment by lyptt** [comment]
Hi @maximkhatskevich, as indicated in the [Specfile documentation](https://github.com/lyptt/struct/wiki/Specfile-format%3A-v1.2) the Specfile DSL is being introduced in `struct` 1.2.0, which is due for release in about 10-15 minutes (waiting on travis builds first!)

If you want to grab this functionality early, feel free to clone the project, then run `rake install` from the root directory. This will install the latest changes so you can start using Specfile right away!

**Comment by maximkhatskevich** [comment]
oops, my bad :) okay, waiting for the release. If I'm watching on the repo, I guess I should receive a notification of some kind when you release?

**Comment by lyptt** [comment]
Yup! I do standard github releases, so you should see a handy notification when this is good to go! `struct` will also notify you of new versions as they're made available as you use it 👍

**Comment by maximkhatskevich** [comment]
Cool! Thanks man! Waiting for it. Want to make Struct work for my project today :)

**Comment by lyptt** [comment]
No problem! If you have any further issues integrating `struct`, let me know. If they're quick fixes I usually do them within the hour 👍
