### ISSUE TITLE
v.1.2 does not work

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#35]
Installed the new release and tried to run `struct --generate` with a Specfile presented in the folder. Got this message: `wrong number of arguments (0 for 1)`. Not sure what does it mean. Any ideas?

**Comment by maximkhatskevich** [comment]
`struct --parse` returns the same

**Comment by lyptt** [comment]
Hi @maximkhatskevich, I'm not entirely sure why that's happening I'm afraid. Does this occur for any of the example projects?

**Comment by maximkhatskevich** [comment]
Let me check actually

**Comment by maximkhatskevich** [comment]
Please note, that I have a Specfile in my folder, but your examples are with project.yml

**Comment by maximkhatskevich** [comment]
Works well for the  framework example

**Comment by lyptt** [comment]
Hi @maximkhatskevich, the main documented example contains a Specfile, and this is what's evaluated for this project. When a project.yml and Specfile are both present, the Specfile is chosen.

**Comment by maximkhatskevich** [comment]
let me see

**Comment by lyptt** [comment]
@maximkhatskevich this sounds like an issue with the DSL then, could you please upload your Specfile so I can take a look?

**Comment by maximkhatskevich** [comment]
when I migrate a project - can I choose Specfile output?

**Comment by lyptt** [comment]
@maximkhatskevich DSL support for migration is still being planned out, this will most likely land in `struct` 1.3.0. Stay tuned for updates!

**Comment by maximkhatskevich** [comment]
okay. the App example works well.

**Comment by lyptt** [comment]
Thanks for confirming that @maximkhatskevich. Most likely one of the DSL methods you're calling has the wrong number of arguments, which is the reason why that error is thrown.

If you could upload your Specfile, I can take a quick look and help you fix the issue.

**Comment by maximkhatskevich** [comment]
Here is my Specfile:
https://www.dropbox.com/s/klq2b8gc34qtxmy/Specfile?dl=0

**Comment by maximkhatskevich** [comment]
Do I use Ruby features in an unexpected way? Variables are not supported? Trying to automate my workflow as much as possible.

**Comment by maximkhatskevich** [comment]
IN case of an error, a hint on line number in Specfile where an issue happened would be much appreciated :)

**Comment by maximkhatskevich** [comment]
Oops, I definitely see 2 errors in syntax where I copied build settings from YAML and didn't wrap it properly into Ruby format - 'DEFINES_MODULE' and 'SKIP_INSTALL'.

**Comment by maximkhatskevich** [comment]
installed struct-1.2.1. Still see the same issue. Trying to simplify the Specfile to nail down the issue.

**Comment by lyptt** [comment]
Hi @maximkhatskevich, I've diagnosed the issue!

Firstly, the `configuration` declaration you've defined outside of a target level is only supported within targets. For project-level configuration, you must always declare your configuration settings for each build configuration.

Secondly, as you've mentioned, there's a few build settings that still use YAML syntax. Fix both of those up and you should be good to go!

One thing to point out is that for a Specfile to be valid, the number of build configurations must match the number of configurations on a project level. When using `configuration do` you can't also use `configuration('my configuration') do`, this is because `configuration do` is shorthand for defining each build configuration individually. So you'll need to apply one or the other depending on your use case.

Please let me know if you need any further assistance on this!

**Comment by maximkhatskevich** [comment]
Okay, got it. Fixing now and will let you know shortly. Please, confirm that using variables and string concatenation is totally valid for Specfile?!

**Comment by lyptt** [comment]
@maximkhatskevich Yes variables are perfectly valid! You can also use functions and any other Ruby syntax you like. This was the main idea behind supporting DSLs, as this allows you to use these features in your DSL for more flexible project generation.

**Comment by lyptt** [comment]
I'm also now tracking #36 to make the error messages for invalid arguments a bit more meaningful.

**Comment by maximkhatskevich** [comment]
Great and thanks for that! Not being able to dynamically construct string values from concatenation/patterns in YAML was a big pain, actually.

**Comment by maximkhatskevich** [comment]
@lyptt I changed the Specfile, now I have another issue:

`uninitialized constant StructCore::SpecBuilderDsl::CommonSettings`

Here is the Specfile: https://www.dropbox.com/s/p4jgkcwjrb8s4di/Specfile?dl=0

**Comment by maximkhatskevich** [comment]
I'm trying to reuse the shared settings as I'm reusing shared Pods in Podfile via `def ...` declaration. Isn't it supported?

**Comment by lyptt** [comment]
Hi @maximkhatskevich, for functions, I believe these must be declared in the correct scope. You could try declaring the function within the spec() statement, this may add it to the correct scope within the file, however I'm not well-versed enough on this aspect of metaprogramming to give you a solid answer.

I'd like to investigate this a bit further myself, as Fastlane for example is perfectly capable of accessing functions in any scope. There's definitely some room for improvement here!

**Comment by maximkhatskevich** [comment]
Okay, let me try.

**Comment by maximkhatskevich** [comment]
Nope. same result if everything is inside the 'spec' declaration :(

**Comment by lyptt** [comment]
Yeah, sounds like there's some tweaks we could do to improve this scenario for sure! I'll make sure it gets tracked for a future release.

**Comment by maximkhatskevich** [comment]
Okay, thank you.

**Comment by lyptt** [comment]
Since all questions have been answered I'm closing this issue. Please file a new issue if you get stuck again!
