### ISSUE TITLE
Public Headers

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#39]
In Xcake a lot of our users use it to generate projects for frameworks so we included a DSL for them  to specify what headers to make public. Struct should have the same.

Let me know if you need help.

**Comment by lyptt** [comment]
Hi @jcampbell05, yes currently all headers are made public in struct. Currently I don't have a clear idea of how to achieve this that fits into the current structure of spec files in struct. I'm happy to accept any ideas on this!

**Comment by jcampbell05** [comment]
@lyptt So how would we currently do it maybe I can brainstorm some ideas :)

**Comment by lyptt** [comment]
My personal opinion on this, is that struct as a tool should absolutely continue to support Objective-C functionality, but adding additional DSL for all of the complexities and edge cases in Objective-C projects isn't really ideal for this tool.

If we can achieve this in a way that is at best automatic, or implicit in nature, without the user having to do any additional work, then that's the best possible outcome. Struct is all about applying sensible defaults whenever possible so you don't have to consider the minutea of Xcode projects.

**Comment by jcampbell05** [comment]
@lyptt so how I did this in Xcake is including a Header added it to the project but didn't create the build phase. Since for apps you don't want to copy the headers, and in frameworks you want to control the visibility levels so you usually speicify where they are by hand (like in cocoapods)

If you wanted to expose them to be public for frameworks there was some DSL that allowed you to tell xcake to create the build phase for headers and which ones to make public, private or a project.

Maybe this could be a seperate module to make add objective-c compatibility. But since Struct is slightly different than Xcake and designed to work alongside Struct then maybe the correct answer here would just be "if you are making frameworks and want to control this stuff then use cocoapods" ?

**Comment by lyptt** [comment]
Hi @jcampbell05, I would be inclined to agree here. Struct isn't meant to be a one stop shop for Objective-C projects, these projects tend to be much more complex than Swift projects and have way more configuration to them.

Objective-C support is intended for backwards compatibility with well-established projects that are a mix of Objective-C and Swift, rather than purely Objective-C.

**Comment by lyptt** [comment]
I think for now we can say 'as intended', until more users are interested in having control over the Headers build phase.
