### ISSUE TITLE
Add support for xcconfig in project generation

### ISSUE THREAD

**Issue by lyptt** [lyptt/struct#4]
Currently struct has no support for xcconfig files as a source for configuration settings.

Proposed schema adjustment would be as follows:

```yaml
configurations:
  debug:
    source: configs/debug.xcconfig
    #optional
    type: debug
targets:
  My app:
    configuration: configs/my-app.xcconfig
  My other app:
    configurations:
      debug: configs/my-app.xcconfig
      release: configs/my-app-release.xcconfig
```

This would replace any existing sources for reading in configuration settings.

Parsing flow as follows:

- If configuration value is a string, treat this as a file reference to an xcconfig file
- If an xcconfig file has been specified, ignore any profiles and overrides
  - Raise a warning if profile or overrides blocks have been defined in addition to an xcconfig file

Generation flow as follows:
- Merge all configuration settings as exists in current behaviour
- When generating configuration objects, associate with a specified xcconfig file if it exists on disk
  - If xcconfig file does not exist on disk, raise a warning and continue

**Comment by lyptt** [comment]
@keith Xcconfig support is now built into struct 🚀

You can give the new functionality a go before its official release by cloning the codebase and running `rake install`, otherwise expect a new release by the end of the week.

**Comment by keith** [comment]
Thanks! I'll try and try it out soon!!
