### ISSUE TITLE
Aggregate Target

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#42]
I've had a request in Xcake for support for aggregate targets we should look into adding this to struct.

**Comment by lyptt** [comment]
Hi @jcampbell05, aggregate targets are usually used to make managing dependencies between targets simpler. Struct already makes this easy and takes care of the hard work for you, so I'm not currently convinced this will be an essential feature. I'm happy to discuss this further however!

**Comment by jcampbell05** [comment]
@lyptt nope I rarely use them these days especially since I use Xcake and Cocoapods. So I would imagine this would make no difference for me.

So I guess it makes sense to close unless someone requests it.

**Comment by lyptt** [comment]
Yup! I definitely agree here. If there are issues managing dependencies between targets, this can be approached with struct functionality rather than relying on more complex Xcode project features.
