### ISSUE TITLE
Replicate high level DSL from Xcake

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#43]
In Xcake we had a high level DSL we could use as a superset, things like generating a unit test for a target. Their was some discussion about adding this to Struct.

**Comment by lyptt** [comment]
Yup I think this is a worthwhile addition, primarly to the Specfile DSL for now to trial it out. I'd like the DSL to be flexible enough so that if you need to you can break it out into its core definitions if you need to adapt it, for example:

```ruby
target 'My app' do
  sources 'src'
  unit_tests 'My app tests' do
    sources 'test'
  end
end
```

Which would be equivalent to the following:

```ruby
target 'My app' do
  sources 'src'
end

target 'My app tests' do
  sources 'test'
  target_reference 'My app'
end
```

**Comment by lyptt** [comment]
No high level DSL is currently planned for struct, if there's further interest in this enhancement please feel free to file a new issue.
