### ISSUE TITLE
Folder References

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#45]
In Xcake we have a way to do Folder references if you include them directly i.e "a/folder/"
this may not make sense if the project is auto-generated but I know some people have asked for it.

**Comment by lyptt** [comment]
Hi @jcampbell05, I'm unsure of how folder references are that beneficial to Xcode projects day to day. Personally I don't think seeing files unrelated to my Xcode project in the source tree is particularly valuable. Xcode as a general editor / file viewer isn't particularly great, so I think for now we can avoid this one unless we get a lot of requests for it.

**Comment by ashhanai** [comment]
Hi @lyptt, in our project, we need to reference some folders to not have all the files in these folders at the same level in bundle. We use third party libraries, which depends on this folder hierarchy. 
Is there any way how to make this possible with the current version of struct? If not, I am adding +1 to this enchantment 😁

**Comment by lyptt** [comment]
Hey @ashhanai, can you explain your use case in a bit more detail? What are you trying to achieve with folder references?
