### ISSUE TITLE
Changing order of files included

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#46]
Is it possible to manually override order files are included ? In xcake we do this by globbing and then re-specifying the files after the glob to force xcake to handle them later.

**Comment by lyptt** [comment]
Hi @jcampbell05, not currently, no. They're added in the order struct finds them. I'm not certain file ordering is particularly essential as currently the files are added in alphabetical order, which I believe will suit most use cases.

**Comment by jcampbell05** [comment]
@lyptt interesting, if thats the case then it may work the same as Xcake anyways as I've found specifying a more specific file path afterwards cause it to be added later in the order.

**Comment by lyptt** [comment]
Yup, another case sensible defaults in struct 👍 I work in a project with a hefty number of Swift files day to day, and if I struggle to find a file, it's usually down to poor folder organisation. If all else fails, the file filter in Xcode is always a decent alternative.

**Comment by jcampbell05** [comment]
@lyptt this isn't so much for file organisation but for helping with build order as file B may have a dependency on C so C has to be built before B :)

**Comment by lyptt** [comment]
Hi @jcampbell05, I don't believe Swift has this issue. I haven't actually encountered this issue myself, however this may be more prevalent for Objective-C projects?

Again I suggest keeping an eye on it, if users really need it we can figure something out.

**Comment by jcampbell05** [comment]
Potentially a Objective-C issue.
