### ISSUE TITLE
Sugar Build Settings

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#47]
In Xcake we have a few sugar build settings which I see Stuct has. But I'm wondering does Struct have one for setting if target is for iPad, iPhone or Universal. and one for Swift Version

**Comment by lyptt** [comment]
Hi @jcampbell05, we don't have any specific DSL for these flags. For SWIFT_VERSION, a sensible default matching the latest Xcode version is defined in the configuration profiles, and this can be overriden with a configuration override. Most likely there's a similar flag for target type however this still requires investigation.

**Comment by jcampbell05** [comment]
@lyptt  shall I make a issue for target type ?

**Comment by lyptt** [comment]
Hi @jcampbell05, I believe we already have target types if you mean :application, :framework, etc. If you're referring to whether a target's an iPhone / iPad / Universal app, we should definitely investigate how Xcode's configuring this.

If it belongs in target configuration, a simple DSL could be added to adjust this. If it's a build setting, we can add a sensible default and document it.

Go ahead and make an issue for it, it's definitely worth investigating to make sure we're not missing anything.
