### ISSUE TITLE
DSL for Target Platform Type

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#51]
Note: This isn't same as the type of target

In Xcake we have a way of configuring the supported platforms of a target, this defines if a app is iPhone Only, iPad Only or Universal.

I'm not sure if this is configurable in the Info.plist but we should look into how Xcode configures it and add it to the DSL if not.

**Comment by lyptt** [comment]
We can do this in a configuration override.

- iPhone-only is the default, no changes needed.
- For iPad: add an override `TARGETED_DEVICE_FAMILY: 2`
- For Universal: add an override `TARGETED_DEVICE_FAMILY: 1,2`

We should add a higher-level DSL for this as part of the main task to integrate an Xcake-like DSL superset.

**Comment by jcampbell05** [comment]
Sounds good 😀 yeah a higher level dsl would be great as those numbers aren't understandable

**Comment by lyptt** [comment]
@jcampbell05 Yup I agree! I guess Xcode developers got lazy that day 😉
