### ISSUE TITLE
Support UUIDs for Target Type

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#59]
For Xcake I had to support UUIDs for Target types, as when I was building a project scaffolder based on Xctemplates the templates used UUIDs rather than nice names like 'application'. It was easier to pass this straight in and pass it to xcodeproj than try to treat it like a symbol and look it up in xcodeproj's constants.

I would very much like to restart my scaffolder on Struct rather than Xcake so this will be useful :)

**Comment by lyptt** [comment]
@jcampbell05 Could you provide some examples? I'm happy to do it if you can provide more detail on what changes would be made 👍

**Comment by jcampbell05** [comment]
So you can see what I did here https://github.com/jcampbell05/xcake/blob/master/lib/xcake/xcode/project.rb#L86

When the type is a symbol i.e ':application' I find the UUID and use that. If the type is a string then I assume it's a UUID and pass it directly in :)

**Comment by lyptt** [comment]
Ah I see! We could definitely support that, potentially by extending DSL functions to look for another parameter, or maybe a hash e.g.:

```ruby
target 'My app' do
  type :uuid => 'XXXX'
end
```

Then we can do a simple type check, `.is_a?(Hash)` then pass through the `:uuid` value

**Comment by jcampbell05** [comment]
@lyptt yup that would work :) will be good to see if I can swap it out for Struct :)  I'm guessing Struct has a serializer for the Spec, Yaml and Json too (For the project recreation)

**Comment by lyptt** [comment]
@jcampbell05 Yup! `StructCore::Specwriter` can generate JSON and YAML spec files.
