### ISSUE TITLE
Add documentation for contributors

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#62]
We should try to add documentation to help contributors understand how everything is set up and document methods when possible (Maybe even generate Yard doc).

**Comment by lyptt** [comment]
We already have docs generated for struct [here](http://www.rubydoc.info/gems/struct), but they should most likely be linked to in the README.md.

**Comment by lyptt** [comment]
@jcampbell05 I agree that dev documentation is very important, maybe a 'Contributing to struct' wiki page would suffice?

**Comment by jcampbell05** [comment]
@lyptt defiantly :)  I'm sure it will be easier to contribute once we've both been working on it, I know that when you first start a project it's hard to do enougth documenting without others to point out where you've missed things :) so It's probably a more as we go along thing

**Comment by lyptt** [comment]
Contributors guide added to the wiki
