### ISSUE TITLE
Downgrade to Ruby 2.0.0

### ISSUE THREAD

**Issue by lyptt** [lyptt/struct#68]
We should downgrade to Ruby 2.0.0 to make installing struct natively possible without RVM.

**Comment by jcampbell05** [comment]
It looks good to me 😀 just wondering why we needed to do the changes with the private attribute ? I think I've managed to find a way of declaring where the private methods start without having to respecify them or is it for readability

**Comment by lyptt** [comment]
@jcampbell05 It's not supported in 2.0.0 unfortunately. Inline private declarations are > 2.0.0 😭

**Comment by jcampbell05** [comment]
I think you can put them on a new line like so:
https://tenderlovemaking.com/2012/09/07/protected-methods-and-ruby-2-0.html

C++ style :D

**Comment by lyptt** [comment]
Ew C++ 😉

I think maybe we could clean this up as part of our general usability refactor? I'd like to get this in asap so way more people can benefit from struct 😄

**Comment by jcampbell05** [comment]
Yeah makes sense
