### ISSUE TITLE
User Defined Macros

### ISSUE THREAD

**Issue by jcampbell05** [lyptt/struct#78]
This is something Xcake handled as well as high level DSL for escaping a string for Objective-C and C

**Comment by lyptt** [comment]
@jcampbell05 could you describe the use case in a bit more detail? Are these for the code templates you can drag in from the right sidebar?

**Comment by jcampbell05** [comment]
@lyptt I mean't preprocessor definitions :)

**Comment by jcampbell05** [comment]
Maybe we can do something like this:

YAML
```
PREPROCCESSOR_MACROS:
- OBJECTIVE_C: @"Hello World"
_ C: "Hello World"
```

JSON 
```
"PREPROCCESSOR_MACROS": {
"OBJECTIVE_C": "$OBJC(Hello World)",
"C": "$C(Hello World)"
}
```

Ruby
```
preprocessor_macro "Objective_C", "Hello World".to_objc
preprocessor_macro "C", "Hello World".to_c
```

**Comment by lyptt** [comment]
Yeah, I need to have a think about how this fits into everything else. I think this could definitely fit into the existing `override '',''` and `configuration` flows. Maybe we could sniff the build setting itself and parse it differently from the others?

**Comment by jcampbell05** [comment]
@lyptt I think having a special accessor is conceptually simpler for us and the user. This is what I did in Xcake so if they set it directly they knew they were on their own but if they used the "sugar" method they knew it was optimized for that build setting and would help them out.

Sniffing may be easier on the user but they may not know we are treating it differently.

Another option is to implement a preprocessor we can run on the build settings, so in the JSON example I use "#OBJC(Hello World" - The #() could be the syntax for a Struct Preprocessor Directive. So #OBJC escapes the text passed to it as a Objective-C String and #C as a C String.

so we can do:

```
override 'PREPROCCESSOR_MACROS', {
"OBJECTIVE_C": "#OBJC{Hey}"
}
```

which becomes 

```
OBJECTIVE_C=\@\"Hey\" 
```

**Comment by lyptt** [comment]
@jcampbell05 I agree sniffing makes it special behaviour that users may be aware of, but we already have implicit enhancements in a lot of what struct does by default. 

I suggest since we already starting to need to post-process build settings before they're inserted to a project, having it implicitly convert this field would be friendlier to the user, as long as it's documented properly.

**Comment by jcampbell05** [comment]
So I suggest we can split this into two sections :)

1. Allow Hashes / Associated Arrays as build settings:

DSL

```
override "PREPROCESSOR_MACRO", {
"MESSAGE" => "Hey"
}
```

JSON
```
 "PREPROCESSOR_MACRO": {
"MESSAGE": "Hey"
}
```

YAML
```
PREPROCESSOR_MACRO:
    MESSAGE: Hey
```

Would be compiled down to "MESSAGE=Hey"

2. So sniffing the build settings is hard as we would need a way to figure out if user wants to escape text for Objective-C or C

We could have a dynamic build setting that is an alias for the actual build setting but it will escape the value the user wants to set i.e 

`override, 'OBJECTIVEC_PREPROCESSOR_MACRO', 'MESSAGE=Hey'`

But I think it may add some complexity like how do we combine these dynamic ones with the standard build setting and in what order.

So instead we could just have a lightweight preprocessing syntax like Xcode has for the build settings (i.e `$(inherited)`). 

`override, 'PREPROCESSOR_MACRO', 'MESSAGE=$OBJC(Hey)'`

**Comment by lyptt** [comment]
Yeah that seems reasonable. So the latter two would belong in overrides still, and we'd post-process that.

**Comment by lyptt** [comment]
This can be achieved by specifying one of `GCC_PREPROCESSOR_DEFINITIONS` or `SWIFT_ACTIVE_COMPILATION_CONDITIONS` in a configuration block. No DSL extension is planned to enhance this currently.
