### ISSUE TITLE
Platform and platform-related profiles should be set/applied on target level only

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#82]
Currently in the example spec files ([here](https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml#L7), [here](https://github.com/lyptt/struct/blob/master/examples/iOS_Framework/project.yml#L13), [here](https://github.com/lyptt/struct/blob/master/examples/iOS_Application/project.yml#L19), [here](https://github.com/lyptt/struct/blob/master/examples/iOS_Application/project.yml#L31), [here](https://github.com/lyptt/struct/blob/master/examples/iOS_App_Watch/project.yml#L7) and [here](https://github.com/lyptt/struct/blob/master/examples/iOS_App_Watch/project.yml#L13)) we apply platform-specific profiles on project level, which doesn't seem to be right. Project can contain targets for different platforms (like iOS and macOS), so platform only make sense on target level, as well as platform-specific profiles.

Correct me if I'm wrong, please.

**Comment by lyptt** [comment]
@maximkhatskevich project-level profiles are separate from target profiles. If you were only doing macOS projects, there wouldn't be a point in declaring iOS-specific configuration information. This is why the profiles exist.

Ultimately though this can be inferred by struct, so removing profiles completely from specfiles as @jcampbell05 has suggested will solve this.

You can track this in #67.

**Comment by maximkhatskevich** [comment]
Agree.

**Comment by jcampbell05** [comment]
Hoping to get a PR for #67 this evening, @maximkhatskevich  :)
