### ISSUE TITLE
Struct should start using GitFlow

### ISSUE THREAD

**Issue by maximkhatskevich** [lyptt/struct#83]
I would highly recommend start using [GitFlow](http://nvie.com/posts/a-successful-git-branching-model/) for branch/release management on this repo. Pushing WIP commits on 'master' branch to the public repo doesn't seem to be a good idea.

**Comment by lyptt** [comment]
@maximkhatskevich agreed. Since there's two devs now that makes sense, after 1.3.0 has gone out, we can make the switch.
